- name: "Mobile App Developments"
  icon: "mobile"
  description: "We develop cross-plaform mobile apps and all aspects involved. 
    BaKu Apps is experienced in delivering the right mobile solution for you."

- name: "Web Development"
  icon: "laptop"
  description: "From website to web app we will develop the right solution for you. If it's .NET, 
    Javascript web technologies or Wordpress, we will find the right tools for your solution."

- name: "IoT & Automation"
  icon: "code-fork"
  description: "We automate data collection using sensors to make farms, warehouses, and machinery smarter. 
    Or perhaps to just brew your own craft beer at home!"

- name: "Training"
  icon: "graduation-cap"
  description: "We provide on-site and remote Xamarin and Flutter training. From introdution to advanced topics. Our expert trainers will take your team to the next level."